version: "3.3"

services:
  nginx:
    volumes:
      - store-src:/usr/src/store
    ports:
      - "80:80"

  store:
    volumes:
      - store-src:/usr/src/app
    environment:
      DEBUG: "false"

  store-mysql:
    environment:
      MYSQL_ROOT_PASSWORD: "roma7Wai"

volumes:
  store-src:
